# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b41d1a614bf613424e930f20430a699170523e26a1e28a0025c4c73961c02758b9946d74fb60d69da1e491983792ee3817b96e4f91883187a3e86b428b68eb

test:
  secret_key_base: c2d759a233a75c3e4c3c7145969b688677b243e1b1fbd35170201573982eeb3ffc02086f90612baf45c4db5ec5d4dc8288adce7abb9585e93cca4c6c79dafdba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
